[book]
authors = ["Boris Zhguchev"]
language = "en"
src = "src"
title = "Documentation for Forester"

[output.html]
additional-js = [
    "mermaid-init.js", "mermaid.min.js",
]


[preprocessor.mermaid]
command = "mdbook-mermaid"